# Uncomment the next line to define a global platform for your project
# platform :ios, ‘9.0’

target 'roomy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Parse'
  pod 'ParseUI'
  pod 'AFNetworking'
  pod 'GooglePlaces'
  pod 'IngeoSDK'
  pod ‘ParseLiveQuery’
  pod 'MBProgressHUD'
  pod 'JSQMessagesViewController'
  pod 'ParseFacebookUtilsV4'
  pod 'pop', '~> 1.0' 
  pod 'FBSDKLoginKit' 
  pod 'IBAnimatable'
  pod ‘JVFloatLabeledTextField'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'FontAwesome-iOS'
  

  # Pods for roomy

end
